### PR TITLE
add missing quote around set arguments in bat

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by hidmic** [comment]
Not just yet, getting:

```bat
if "%PYTHONPATH:~-1%"==";" set "PYTHONPATH=%PYTHONPATH:~0,-1%"
'if' is not recognized as an internal or external command,
operable program or batch file.
```

with these changes.

**Comment by dirk-thomas** [comment]
@hidmic Please try again with the updated patch.

**Comment by jacobperron** [comment]
Approval under the assumption this fixes things (I haven't given it a try yet).

**Comment by dirk-thomas** [comment]
> I haven't given it a try yet.

I can wait for that - for this part it's better to double/triple check.

**Comment by hidmic** [comment]
Took me a while to get back to this, but I can confirm the patch works just fine. Thanks!

**Pull request merged**
