### PR TITLE
Drop dependencies from test execution

### PR DESCRIPTION
**Pull request by cottsay**
The current model requires that packages have already finished building prior to invoking tests, meaning that there aren't any ordering constraints on test execution.

Before we can merge this PR, we have some work to do in the ROS 2 codebase, where there is global state among tests and possible collisions during execution. Once we've developed a cohesive plan for dealing with those collisions, we can consider increasing the parallelism here.

### CODE REVIEW

**Comment by cottsay** [comment]
Prototype builds:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19313/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13844/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20033/)

**Review by nuclearsandwich — APPROVED** [review]
@cottsay and I had a good conversation about this change and the reasons we can't yet merge it. I'd really like to see the info in that discussion added to the PR body but I totally agree with the approach.

**Comment by scpeters** [comment]
I understand that this can't be merged in the nearer term, but would you accept an earlier merge of this functionality behind an `--ignore-dependencies` flag?

**Comment by scpeters** [comment]
> I understand that this can't be merged in the nearer term, but would you accept an earlier merge of this functionality behind an `--ignore-dependencies` flag?

Ok, it looks like you have added a feature flag for this. I think I use this feature by setting the following environment variable:

~~~
export COLCON_FEATURE_FLAGS=drop_test_deps
~~~

Is that right?

**Comment by cottsay** [comment]
> Is that right?

That's correct. As soon as I get readthedocs deployments running again, I'll add information on the semantics of feature flags.

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
