### PR TITLE
Allow ignore_marker to be a dangling symlink

### PR DESCRIPTION
**Pull request by rotu**
As per https://github.com/ros-infrastructure/rep/pull/256

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Have you tried running the patch?

**Comment by rotu** [comment]
> Have you tried running the patch?

I hadn't, as can be seen from CI!

**Comment by rotu** [comment]
This patch now works correctly and is ready for review

**Comment by dirk-thomas** [comment]
With the REP update merged (ros-infrastructure/rep#256) I will go ahead ad merge this.

**Comment by chapulina** [comment]
:farmer: 

The Appveyor build failed after this PR was merged: 

https://ci.appveyor.com/project/dirk-thomas/colcon-core/history

```
[5.219s] ERROR    colcon.colcon_core.event_reactor:event_reactor.py:86 Exception in event handler extension 'extension3': custom exception
Traceback (most recent call last):
  File "C:\projects\colcon-core\colcon_core\event_reactor.py", line 78, in _notify_observers
    retval = observer(event)
  File "C:\projects\colcon-core\test\test_event_reactor.py", line 43, in __call__
    raise RuntimeError('custom exception')
RuntimeError: custom exception
```

**Comment by dirk-thomas** [comment]
@chapulina The correct error message of the test failure is:

```
>           assert error.call_count == 2
E           AssertionError: assert 1 == 2
E            +  where 1 = <MagicMock name='error' id='872644937432'>.call_count
test\test_event_reactor.py:80: AssertionError
```

I retriggered the build and expect it to pass (since it passed before).

**Comment by dirk-thomas** [comment]
@chapulina See #345 which makes the test (less | not) flaky.

**Pull request merged**
