### PR TITLE
redirect pytest warnings summary to stderr

### PR DESCRIPTION
**Pull request by dirk-thomas**
With the goal to make them more visible. A package can always opt to filter the warnings using e.g. the `filterwarnings` option in a `pytest.ini` file.

### CODE REVIEW

**Comment by rotu** [comment]
Why reparse stdout instead of making sure these messages get sent to the correct stream in the first place?

**Comment by dirk-thomas** [comment]
> Why reparse stdout instead of making sure these messages get sent to the correct stream in the first place?

Do you have a suggestion how to achieve that?

**Comment by rotu** [comment]
either with the `pytest_runtest_logreport`, `pytest_terminal_summary` or `pytest_warning_captured` hook. 

https://docs.pytest.org/en/latest/_modules/_pytest/hookspec.html

**Comment by dirk-thomas** [comment]
Closing in favor of #338.

**Comment by tylerjw** [comment]
Sadly it looks like the ninja project itself considers "feature" to be not-useful: https://github.com/ninja-build/ninja/issues/1537

Their reasoning is that the error message is not useful without the context of what command caused it and therefore if you care about why it failed, you also care about what command was called when it failed.

**Comment by tylerjw** [comment]
The suggested solution there is this:

```bash
NINJA_STATUS="[ninja][%f/%t]
filter() {
  local l n
  while read -r l; do
    n=${l#\[ninja\]}
    [ "x$l" != "x$n" ] && printf "%s\n" "$n" || printf "%s\n" "$l" >&2
  done
}

NINJA_STATUS="[ninja][%f/%t] " ninja | filter
```

I don't know how difficult this would be to implement (here) but it is simple enough.

**Comment by dirk-thomas** [comment]
@tylerjw Your comments seem to be off topic for this ticket. colcon/colcon-cmake#67 seems to be discussing what you are referring to. Please consider to contribute a pull request to `colcon-cmake` to implement custom logic to separate the Ninja output.

**Comment by tylerjw** [comment]
I'm sorry about that... I'll re-target my comments.

**Pull request closed without merging**
