### PR TITLE
Implement create_hook_append_value

### PR DESCRIPTION
**Pull request by cottsay**
It looks like support for this flag was templated, but was never implemented. I'd like to use it in the same way we're currently using the prepending variant.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Can you please describe the use case where you want to use that new environment hook.

Also please provide corresponding PRs for other shells where needed (e.g. `powershell`).

**Comment by cottsay** [comment]
> Can you please describe the use case where you want to use that new environment hook.

The use case is a package which wishes to append a value to an environment variable which contains a list of paths. The behavior should resemble the mechanism which places a value at the front.

> Also please provide corresponding PRs for other shells where needed.

I forgot that there were other supported shells in other colcon extensions. I'll open PRs for those.

**Comment by dirk-thomas** [comment]
> The use case is a package which wishes to append a value to an environment variable which contains a list of paths.

Can you please describe the specific use case, which package, what environment variable.

**Comment by cottsay** [comment]
> Can you please describe the specific use case, which package, what environment variable.

I need to append `/usr` to `CMAKE_PREFIX_PATH` in a Bloom patch for `ros_workspace` for RHEL. The workaround is necessary because the fallback search path mechanism in CMake that relies on the `PATH` variable doesn't work the same on RHEL as it does on other platforms because `/bin` and `/sbin` sometimes come before `/usr/bin` and `/usr/sbin`, resulting in some `FindFOO.cmake` modules reporting bad include directories like `/include`. This needs to work for downstream RPM packages (which is why I'm also enhancing `ament_package`), and also local workspaces (which is why I'm enhancing colcon).

I really don't understand the strong push-back on this change - clearly it was a conceived and left unimplemented long before this use case. Whatever the reason, I hope you'll find this explanation sufficient to move forward with this clear-cut enhancement.

**Comment by cottsay** [comment]
> > Also please provide corresponding PRs for other shells where needed.
>
> I forgot that there were other supported shells in other colcon extensions. I'll open PRs for those.

Neither `colcon_bash` nor `colcon_zsh` have existing hooks for prepend, so I don't think they need hooks for appending either. I added a hook for `colcon-powershell`: colcon/colcon-powershell#30

**Comment by dirk-thomas** [comment]
> I really don't understand the strong push-back on this change

My questions are not "strong push-back". Knowing the use case why a certain patch was proposed and merged not only helps in the review process but also records that information for future readers. That could e.g. be helpful if something related to this breaks in the future to trace the use case it was needed for which would be affected.

> I hope you'll find this explanation sufficient to move forward with this clear-cut enhancement.

I haven't tried the patch myself but am convinced it works as desired for your use case. Thanks for the patch. Merging...

**Comment by cottsay** [comment]
> Knowing the use case why a certain patch was proposed and merged not only helps in the review process but also records that information for future readers. That could e.g. be helpful if something related to this breaks in the future to trace the use case it was needed for which would be affected.

You're right, I apologize. That was a rash accusation.

> I haven't tried the patch myself but am convinced it works as desired for your use case.

I appreciate it, thanks for taking a look.

**Pull request merged**
