### PR TITLE
Change import order to pass flake8-import-order, reenable in CI

### PR DESCRIPTION
**Pull request by cottsay**
Regression caused by #396

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Can you please describe the regression fixed by this patch.

**Comment by cottsay** [comment]
> Can you please describe the regression fixed by this patch.

I mean, I think the title makes it pretty clear that consistent import ordering regressed, but here is the flake8 output from running `python3 -s setup.py pytest`:
```
test/test_flake8.py:56: AssertionError
-------------------------------------------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------------------------------------------

1     I100 Import statements are in the wrong order. 'from colcon_core.subprocess import check_output' should be before 'from colcon_core.task.python import get_setup_data'
-------------------------------------------------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------------------------------------------------
/home/cottsay/colcon-core/colcon_core/task/python/build.py:27:1: I100 Import statements are in the wrong order. 'from colcon_core.subprocess import check_output' should be before 'from colcon_core.task.python import get_setup_data'
from colcon_core.subprocess import check_output
^
flake8 reported 1 errors
```

The output suggests that the test is running with flake8-import-order 0.18.1, which is the newest on pypi.org. I have no idea why CI isn't catching it, but the fix is pretty clear.

**Comment by dirk-thomas** [comment]
> I think the title makes it pretty clear that consistent import ordering regressed,

I updated the title to clarify that this is only a fix for linting.

> The output suggests that the test is running with flake8-import-order 0.18.1, which is the newest on pypi.org. I have no idea why CI isn't catching it, but the fix is pretty clear.

What output are you referring to? The latest builds of target branch on Travis CI as well as AppVeyor don't show this error message. Also I don't think CI is even installing `flake8-import-order`.

**Comment by cottsay** [comment]
> Also I don't think CI is even installing flake8-import-order.

Well that's probably why I'm seeing the error locally but CI isn't catching it.

The `setup.cfg` says it should be installed: https://github.com/colcon/colcon-core/blob/6e101f379e87e40001be5ef2b349176d8fe6027e/setup.cfg#L49

Should I update CI to meet the test requirements that the `setup.cfg` dictates?

**Comment by dirk-thomas** [comment]
> Should I update CI to meet the test requirements that the `setup.cfg` dictates?

That would be good. I don't recall why it was explicitly skipped (https://github.com/colcon/colcon-core/blob/6e101f379e87e40001be5ef2b349176d8fe6027e/.travis.yml#L21).

**Comment by cottsay** [comment]
> I don't recall why it was explicitly skipped

Here's the commit in which it was removed: https://github.com/colcon/colcon-core/pull/1/commits/d185af5e1507146e180857b29602d60ede0ad908

From the commit message, "it produces different results", or at least it did in 2018. Maybe worth another try now.

**Comment by cottsay** [comment]
Travis' builds for Linux is green, and so is AppVeyor. Whatever the issue was in 2018, I can't seem to reproduce it now.

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
