### PR TITLE
Merge the pytest configuration

### PR DESCRIPTION
**Pull request by cottsay**
The addition of the pytest.ini is eclipsing the pytest configuration that was already present in the setup.cfg.

There can be only one.

This moves the configuration from the pytest.ini into the setup.cfg and re-adjusts the warnings filter to get things passing on all of Ubuntu, macOS, and Windows.

### CODE REVIEW

**Comment by j-rivero** [comment]
> The addition of the pytest.ini is eclipsing the pytest configuration that was already present in the setup.cfg.
> 
> There can be only one.

I'm a total ignorant in these python configurations, excuse me if there something obvious I'm missing. Is there any benefit in moving configuration from pytest.ini to setup.cfg instead of doing the opposite?

A quick search drove me to https://docs.pytest.org/en/6.2.x/customize.html:
> Warning
>
> Usage of setup.cfg is not recommended unless for very simple use cases. .cfg files use a different parser than pytest.ini and tox.ini which might cause hard to track down problems. When possible, it is recommended to use the latter files, or pyproject.toml, to hold your pytest configuration.

**Comment by mikepurvis** [comment]
+1 for me from moving toward `pyproject.toml` instead. I've been using Poetry on some recent projects and I'm a pretty big fan.

**Comment by cottsay** [comment]
I really don't care if the data is in `setup.cfg`, `pytest.ini`, or `pyproject.toml`. I just want it to work, and it doesn't right now.

Looks like using `pytest.ini` appears to pass as well.

For the record, I'm not aware of any other colcon repos storing pytest config outside of `setup.cfg`. While I don't care which file we use, I do care that it's consistent. If we're going to change to `pytest.ini` here, I recommend we change it everywhere. I'm not sure I'm willing to undertake that.

**Comment by j-rivero** [comment]
> For the record, I'm not aware of any other colcon repos storing pytest config outside of `setup.cfg`. While I don't care which file we use, I do care that it's consistent. If we're going to change to `pytest.ini` here, I recommend we change it everywhere. I'm not sure I'm willing to undertake that.

Consistency seems an strong reason to keep things in the original place, if we need to replace all the colcon repositories it probably does not worth the effort at this point.

**Pull request merged**
